{"version":"3.8.2","messages":["\nAn error occurred while loading ./spec/features/users/sign_in_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mSign in\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User cannot sign in if not registered\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I do not exist as a user\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I sign in with valid credentials\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see an invalid credentials message\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31muser cannot sign in if not registered\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0msignin(\u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mtest@example.com\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mplease123\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m)\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[1;34;4mI18n\u001b[0m.t \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mdevise.failure.not_found_in_database\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[35mauthentication_keys\u001b[0m: \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31memail\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/sign_in_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/users/sign_out_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mSign out\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User signs out successfully\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I sign out\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see a signed out message\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31muser signs out successfully\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0muser = \u001b[1;34;4mFactoryBot\u001b[0m.create(\u001b[33m:user\u001b[0m)\u001b[0m\n\u001b[31m      \u001b[0msignin(user.email, user.password)\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[1;34;4mI18n\u001b[0m.t \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mdevise.sessions.signed_in\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/sign_out_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/users/user_delete_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mUser delete\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m, \u001b[33m:js\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mafter\u001b[0m(\u001b[33m:each\u001b[0m) \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[1;34;4mWarden\u001b[0m.test_reset!\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User can delete own account\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I delete my account\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I should see an account deleted message\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/user_delete_spec.rb:8:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/users/user_edit_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mUser edit\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mafter\u001b[0m(\u001b[33m:each\u001b[0m) \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[1;34;4mWarden\u001b[0m.test_reset!\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User changes email address\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I change my email address\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see an account updated message\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/user_edit_spec.rb:8:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/users/user_index_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mUser index page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mafter\u001b[0m(\u001b[33m:each\u001b[0m) \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[1;34;4mWarden\u001b[0m.test_reset!\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User listed on index page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I visit the user index page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see my own email address\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/user_index_spec.rb:8:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/users/user_show_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mUser profile page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mafter\u001b[0m(\u001b[33m:each\u001b[0m) \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[1;34;4mWarden\u001b[0m.test_reset!\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: User sees own profile\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I visit the user profile page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see my own email address\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/users/user_show_spec.rb:8:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/visitors/about_page_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mAbout page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: Visit the 'about' page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am a visitor\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I visit the 'about' page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see \"About the Website\"\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mVisit the about page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0mvisit \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mpages/about\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mAbout the Website\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/visitors/about_page_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/visitors/home_page_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mHome page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: Visit the home page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am a visitor\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I visit the home page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see \"Welcome\"\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mvisit the home page\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0mvisit \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31m/home\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mWelcome\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/visitors/home_page_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/visitors/navigation_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mNavigation links\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: View navigation links\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am a visitor\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I visit the home page\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see \"home,\" \"sign in,\" and \"sign up\"\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mview navigation links\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0mvisit root_path\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mHome\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mSign in\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/visitors/navigation_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/features/visitors/sign_up_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mfeature \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mSign Up\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[33m:devise\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m# Scenario: Visitor can sign up with valid email address and password\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Given I am not signed in\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   When I sign up with a valid email address and password\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[1;30m#   Then I see a successful sign up message\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0mscenario \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mvisitor can sign up with valid email address and password\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0msign_up_with(\u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mtest@example.com\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mplease123\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m, \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mplease123\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m)\u001b[0m\n\u001b[31m      \u001b[0mtxts = [\u001b[1;34;4mI18n\u001b[0m.t( \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mdevise.registrations.signed_up\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m), \u001b[1;34;4mI18n\u001b[0m.t( \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31mdevise.registrations.signed_up_but_unconfirmed\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m)]\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(page).to have_content(\u001b[35m\u001b[1;35m/\u001b[0m\u001b[35m.*#{txts[0]}\u001b[0m\u001b[35m.*|.*#{txts[1]}\u001b[0m\u001b[35m.*\u001b[1;35m/\u001b[0m\u001b[35m\u001b[0m)\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `feature' for main:Object\u001b[0m\n\u001b[36m# ./spec/features/visitors/sign_up_spec.rb:5:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n","\nAn error occurred while loading ./spec/policies/user_policy_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0mpermissions \u001b[33m:index?\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mit\u001b[0m \u001b[31m\u001b[1;31m\"\u001b[0m\u001b[31mdenies access if not an admin\u001b[1;31m\"\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(\u001b[1;34;4mUserPolicy\u001b[0m).not_to permit(current_user)\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mit\u001b[0m \u001b[31m\u001b[1;31m\"\u001b[0m\u001b[31mallows access for an admin\u001b[1;31m\"\u001b[0m\u001b[31m\u001b[0m \u001b[32mdo\u001b[0m\u001b[0m\n\u001b[31m      \u001b[0m\u001b[32mexpect\u001b[0m(\u001b[1;34;4mUserPolicy\u001b[0m).to permit(admin)\u001b[0m\n\u001b[31m    \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m\u001b[32mend\u001b[0m\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  undefined method `permissions' for RSpec::ExampleGroups::UserPolicy:Class\u001b[0m\n\u001b[36m# ./spec/policies/user_policy_spec.rb:8:in `block in \u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# ./spec/policies/user_policy_spec.rb:1:in `\u003ctop (required)\u003e'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'\u001b[0m\n\u001b[36m# /usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'\u001b[0m\n"],"examples":[],"summary":{"duration":0.000278758,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":12},"summary_line":"0 examples, 0 failures, 12 errors occurred outside of examples"}